In [10]:
import pandas as pd
import numpy
import csv
from itertools import zip_longest
from itertools import chain


Data_Random=pd.read_excel("Darcy.xlsx", sheet_name="AUGUST 2021 - USD")


Data_CPQ=pd.read_excel("CPQ.xlsx")

INDEX1=[]
INDEX2=[]
Extracted_price=[]


for i in Data_Random["SKU"]:
    for j in Data_CPQ["SKU"]:
        if i==j:
            INDEX1.append(Data_CPQ[Data_CPQ["SKU"]==i].index.values)
            
flatten_index1 = list(chain.from_iterable(INDEX1))
print(flatten_index1)

for i in flatten_index1:
    Extracted_price.append(Data_CPQ.at[i,"Price"])
    
print(Extracted_price)

Table=[Extracted_price]
export_data = zip_longest(*Table, fillvalue = '')
with open('EX.csv', 'w', encoding="ISO-8859-1", newline='') as myfile:
      wr = csv.writer(myfile)
      wr.writerow(("CPQ_price"," "))
      wr.writerows(export_data)
myfile.close()
    
    
Data_CPQ

[1091, 1132, 1039, 946, 1150, 1155, 1192, 879, 1339, 1443, 1382, 1639, 808, 754, 658, 2554, 2539, 541, 2639, 2803, 2769, 2839, 2740, 2817, 2777, 2820, 2649, 2798, 318, 2695, 236, 321, 262, 345, 270, 467, 352, 332, 439, 2558, 233, 440, 433, 444, 2624, 2635, 381, 487, 363, 2604, 394, 2864, 2892, 2903]
[70.0, 120.0, 6.5, 20.0, 14.5, 105.0, 125.0, 20.0, 310.0, 200.0, 250.0, 40.0, 23.0, 45.0, 5.5, 700.0, 115.0, 120.0, 230.0, 550.0, 150.0, 260.0, 360.0, 325.0, 250.0, 350.0, 140.0, 150.0, 145.0, 725.0, 95.0, 220.0, 100.0, 140.0, 310.0, 500.0, 220.0, 750.0, 180.0, 45.0, 140.0, 660.0, 220.0, 450.0, 70.0, 350.0, 375.0, 455.0, 190.0, 70.0, 140.0, 40.0, 40.0, 575.0]

       PriceListName          SKU  Price
0     UFMX 1711E V5    1110-001-3  30.00
1     UFMX 1711E V5    1110-002-0  21.00
2     UFMX 1711E V5    1140-200-0  32.00
3     UFMX 1711E V5    1140-201-0  20.00
4     UFMX 1711E V5    1140-202-7  23.00
...              ...          ...    ...
3302  UFMX 1711E V5    9290-267-7   5.00
3303  UFMX 1711E V5    9320-001-0   0.75
3304  UFMX 1711E V5    9320-002-0   1.15
3305  UFMX 1711E V5    9320-003-0   2.25
3306  UFMX 1711E V5   9320-9001-1   3.00

[3307 rows x 3 columns]