In [2]:
import pandas as pd
import csv
from itertools import zip_longest

Job_title=["Radiation Monitor1","Lab technician1",
           "Data scientist1","Data entry1", "Data_Analyst1",
           "Data_analyst_Quebec","Data_analyst_Alberta", 
           "Vocational teacher","Data_analyst_Vancouver",
           "Data_entry_FedEx","Warehouse_Ontario",
           "Data_entry_supervisor","Data_entry_Ontario",
           "Data_Entry_Surry","Early_houseware",
           "Data_Entry_Kitchener","Evining_warehouse",
           "Warehouse_Winnipeg1", "Quality_Assurance_Winnipeg",
           'Data_Analyst(SEO)','Data_Entry_Winnipeg1', 
           'Data_Entry_Simcoe','Data_Entry(Medical_Winnipeg)', 
           'Warehouse_Winnipeg2','Data_Entry_Winnipeg2',
           'Data_Scientist_Winnipeg','Data_Analyst_Revelstock','Data_Analyst_Alberta',
           'Arctic_Beverages_Winnipeg','Data_Analyst_Green_Bee3','Etobicoke(ON)',
           'UPS','Data_Entry(Randstad)_Winnipeg','Goodbye_data_analyst','Data_Entry_Winnipeg',
           'Data_Entry_Clerk_Winnipeg','Data_Analyst_Toronto','Data_Entry_Clerk_Toronto',
           'Data_Analyst_Surry','Junior_Analyst',
           'Data_scientist','Data_Entry_Winnipeg_Drop_Green',
           'Reporting_Analyst_Winnipeg',
           'Warehouse_Bernuby',
           'Warehouse_Richmond','Technical_Analyst_Toronto',
           'Data_Entry_Dark_International_Winnipeg',
           'Data_and_statistical_analyst_Winnipeg','Data_Analyst_Parmida_Toronto',
           'Data_Entry_David_Aplin_Winnipeg','Data_Analyst_Winnipeg_Emerge_knowledge_designe',
           'Data_Analyst_Headingley_Data_Analyst','Data_Entry_Toronto',
           'Quality_Analyst_Toronto',
           'Data_Entry_Vancouver_Alcon_Tool','Administrator_Database_Vancouver']
deadline=["2020.01.14",'2021.01.09','2021.01.02','2020.12.20',
          '2021.01.03','2021.01.04', '2021.01.06','2021.01.06',
          '2021.01.07','2021.01.12','2021.01.21', "2021.02.03",
          "2021.01.24",'2021.01.24',"ASAP","ASAP","ASAP","2021.02.05","2021.02.01",'ASAP','2021.01.29',
          "ASAP","ASAP","ASAP","ASAP","ASAP","ASAP",'ASAP','ASAP','ASAP',
          'ASAP','ASAP','ASAP','ASAP','ASAP',
          'ASAP','ASAP','ASAP','ASAP','ASAP','ASAP','ASAP',
          'ASAP','ASAP','ASAP','ASAP','ASAP','ASAP','ASAP','ASAP','ASAP','ASAP','ASAP','ASAP',
          'ASAP','ASAP']
Status=['Applied','Applied','Done','Applied','Applied','Applied',
        'Applied','Applied','Applied','Applied','Applied','Applied',
        'Applied','Applied','Applied','Applied',
        'Applied',"Applied","Applied",'Done','Done', 'Done','Applied',
        'Applied','Applied','Applied','Applied','Applied','Done',
        'Applied','Applied','Applied','Applied',
        'Applied','Applied','Applied','Applied',
        'Applied','Applied','Applied','Applied',
        'Applied','Applied','Applied','Applied','Applied','Applied',
        'Applied','Applied','Applied','Applied','Applied','Applied',
        'Applied','Applied','Applied']

Table=[Job_title,deadline,Status]

export_data = zip_longest(*Table, fillvalue = '')
with open('Job_app.csv', 'w', encoding="ISO-8859-1", newline='') as myfile:
      wr = csv.writer(myfile)
      wr.writerow(("Job_title", "Deadline", "Status"))
      wr.writerows(export_data)
myfile.close()

df1 = pd.read_csv("Job_app.csv")

df1

                                         Job_title    Deadline   Status
0                               Radiation Monitor1  2020.01.14  Applied
1                                  Lab technician1  2021.01.09  Applied
2                                  Data scientist1  2021.01.02     Done
3                                      Data entry1  2020.12.20  Applied
4                                    Data_Analyst1  2021.01.03  Applied
5                              Data_analyst_Quebec  2021.01.04  Applied
6                             Data_analyst_Alberta  2021.01.06  Applied
7                               Vocational teacher  2021.01.06  Applied
8                           Data_analyst_Vancouver  2021.01.07  Applied
9                                 Data_entry_FedEx  2021.01.12  Applied
10                               Warehouse_Ontario  2021.01.21  Applied
11                           Data_entry_supervisor  2021.02.03  Applied
12                              Data_entry_Ontario  2021.01.24  Applied
13                                Data_Entry_Surry  2021.01.24  Applied
14                                 Early_houseware        ASAP  Applied
15                            Data_Entry_Kitchener        ASAP  Applied
16                               Evining_warehouse        ASAP  Applied
17                             Warehouse_Winnipeg1  2021.02.05  Applied
18                      Quality_Assurance_Winnipeg  2021.02.01  Applied
19                               Data_Analyst(SEO)        ASAP     Done
20                            Data_Entry_Winnipeg1  2021.01.29     Done
21                               Data_Entry_Simcoe        ASAP     Done
22                    Data_Entry(Medical_Winnipeg)        ASAP  Applied
23                             Warehouse_Winnipeg2        ASAP  Applied
24                            Data_Entry_Winnipeg2        ASAP  Applied
25                         Data_Scientist_Winnipeg        ASAP  Applied
26                         Data_Analyst_Revelstock        ASAP  Applied
27                            Data_Analyst_Alberta        ASAP  Applied
28                       Arctic_Beverages_Winnipeg        ASAP     Done
29                         Data_Analyst_Green_Bee3        ASAP  Applied
30                                   Etobicoke(ON)        ASAP  Applied
31                                             UPS        ASAP  Applied
32                   Data_Entry(Randstad)_Winnipeg        ASAP  Applied
33                            Goodbye_data_analyst        ASAP  Applied
34                             Data_Entry_Winnipeg        ASAP  Applied
35                       Data_Entry_Clerk_Winnipeg        ASAP  Applied
36                            Data_Analyst_Toronto        ASAP  Applied
37                        Data_Entry_Clerk_Toronto        ASAP  Applied
38                              Data_Analyst_Surry        ASAP  Applied
39                                  Junior_Analyst        ASAP  Applied
40                                  Data_scientist        ASAP  Applied
41                  Data_Entry_Winnipeg_Drop_Green        ASAP  Applied
42                      Reporting_Analyst_Winnipeg        ASAP  Applied
43                               Warehouse_Bernuby        ASAP  Applied
44                              Warehouse_Richmond        ASAP  Applied
45                       Technical_Analyst_Toronto        ASAP  Applied
46          Data_Entry_Dark_International_Winnipeg        ASAP  Applied
47           Data_and_statistical_analyst_Winnipeg        ASAP  Applied
48                    Data_Analyst_Parmida_Toronto        ASAP  Applied
49                 Data_Entry_David_Aplin_Winnipeg        ASAP  Applied
50  Data_Analyst_Winnipeg_Emerge_knowledge_designe        ASAP  Applied
51            Data_Analyst_Headingley_Data_Analyst        ASAP  Applied
52                              Data_Entry_Toronto        ASAP  Applied
53                         Quality_Analyst_Toronto        ASAP  Applied
54                 Data_Entry_Vancouver_Alcon_Tool        ASAP  Applied
55                Administrator_Database_Vancouver        ASAP  Applied