In [12]:
import pandas as pd
import numpy
import csv
from itertools import zip_longest

data1=pd.read_excel("Darcy.xlsx")
data2=pd.read_excel("CPQ_UPH.xlsx")

skus1=[]
grade11=[]


skus2=[]
grade22=[]


SKUS1=data1['GRADE (UPH)']
SKUS2=data2['GradeGrouping']

grade1=data1["SKU"]
grade2=data2["Catalog"]


Price2=data2["Price"]
price2=[]

for i in SKUS1:
    skus1.append(i)

for i in SKUS2:
    skus2.append(i)

for i in grade1:
    grade11.append(i)
    
for i in grade2:
    grade22.append(i)
    
for i in Price2:
    price2.append(i)



a=[skus1,grade11]
b=[skus2,grade22]
c=price2
extracted_price=[]
extracted_skus=[]
extracted_grades=[]
length1=len(a[0])
length2=len(b[0])


print("***************************************************")
print("The length of column in our Excel file: ")
print(length1)
print("***************************************************")
print("The length of the column in the file made for CPQ: ")
print(length2)
print("***************************************************")



for j in range(0,length1,1):
    for k in range(0,length2,1):
        if ((a[0][j])==b[0][k]) and (a[1][j]==b[1][k]):
            print(b[0][k])
            print(b[1][k])
            print(c[k])
            extracted_skus.append(b[0][k])
            extracted_grades.append(b[1][k])
            extracted_price.append(c[k])
            
print(extracted_price)
            
print("Length of the extracted grades: ")
print(len(extracted_grades))


# Exporting the extracted data to the spreadsheet

d=[extracted_price]
export_data=zip_longest(*d, fillvalue='')
with open("Ex.csv", "w", encoding="ISO-8859-1", newline='') as CPQ:
    wr=csv.writer(CPQ)
    wr.writerow(("Price"," "))
    wr.writerows(export_data)
CPQ.close()

***************************************************
The length of column in our Excel file:
100
***************************************************
The length of the column in the file made for CPQ:
10862
***************************************************
100
37129-01
1125
200
37024-03
1015
300
37132-08
1215
400
37133-08
1260
600
37116-03
1425
700
37116-87
1720
800
37116-40
1870
10
30136-01
1150
20
30136-20
890
800
37136-14
1720
30
30137-08
1020
100
37137-14
1400
40
30192-11
710
200
37192-03
1890
300
37192-19
1590
50
30193-06
1025
60
30193-20
1200
400
37193-16
1635
600
37237-03
1825
70
30154-01
1225
700
37095-01
1720
800
37095-91
1720
100
37195-07
1125
200
37195-97
1265
300
37127-01
1490
400
37127-86
1585
600
37128-14
1325
700
37128-S3
1820
10
30125-02
550
20
30073-02
370
800
37156-03
1365
100
37157-14
850
30
30179-D2
210
40
30151-01
1450
200
37151-01
1840
50
31232-15
1025
300
37232-91
1515
10
30024-01
645
10
30095-15
800
10
30148-S3
1450
10
30160-92
950
[1125, 1015, 1215, 1260, 1425, 1720, 1870, 1150, 890, 1720, 1020, 1400, 710, 1890, 1590, 1025, 1200, 1635, 1825, 1225, 1720, 1720, 1125, 1265, 1490, 1585, 1325, 1820, 550, 370, 1365, 850, 210, 1450, 1840, 1025, 1515, 645, 800, 1450, 950]
Length of the extracted grades:
41